# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies-App-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movies-App-iOS
pod 'Kingfisher'

  target 'Movies-App-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Movies-App-iOSUITests' do
    # Pods for testing
  end

end
